<?php

declare(strict_types=1);

return [
    'ngbm_rule' => [
        ['id' => 1, 'status' => 1, 'layout_id' => 11, 'comment' => ''],
        ['id' => 2, 'status' => 0, 'layout_id' => 12, 'comment' => ''],
        ['id' => 3, 'status' => 1, 'layout_id' => 13, 'comment' => ''],
        ['id' => 4, 'status' => 1, 'layout_id' => 14, 'comment' => ''],
        ['id' => 5, 'status' => 1, 'layout_id' => null, 'comment' => ''],
        ['id' => 6, 'status' => 1, 'layout_id' => 16, 'comment' => ''],
        ['id' => 7, 'status' => 1, 'layout_id' => 17, 'comment' => ''],
        ['id' => 8, 'status' => 1, 'layout_id' => 1, 'comment' => ''],
        ['id' => 9, 'status' => 1, 'layout_id' => 19, 'comment' => ''],
        ['id' => 10, 'status' => 1, 'layout_id' => 20, 'comment' => ''],
        ['id' => 11, 'status' => 1, 'layout_id' => 21, 'comment' => ''],
    ],
    'ngbm_rule_data' => [
        ['rule_id' => 1, 'enabled' => 1, 'priority' => 10],
        ['rule_id' => 2, 'enabled' => 1, 'priority' => 9],
        ['rule_id' => 3, 'enabled' => 1, 'priority' => 8],
        ['rule_id' => 4, 'enabled' => 1, 'priority' => 7],
        ['rule_id' => 5, 'enabled' => 0, 'priority' => 6],
        ['rule_id' => 6, 'enabled' => 0, 'priority' => 5],
        ['rule_id' => 7, 'enabled' => 1, 'priority' => 4],
        ['rule_id' => 8, 'enabled' => 1, 'priority' => 3],
        ['rule_id' => 9, 'enabled' => 1, 'priority' => 2],
        ['rule_id' => 10, 'enabled' => 1, 'priority' => 1],
        ['rule_id' => 11, 'enabled' => 1, 'priority' => 0],
    ],
    'ngbm_rule_target' => [
        ['id' => 1, 'status' => 1, 'rule_id' => 1, 'type' => 'ezlocation', 'value' => 72],
        ['id' => 2, 'status' => 1, 'rule_id' => 1, 'type' => 'ezlocation', 'value' => 73],
        ['id' => 3, 'status' => 0, 'rule_id' => 2, 'type' => 'ezlocation', 'value' => 74],
        ['id' => 4, 'status' => 1, 'rule_id' => 3, 'type' => 'ezlocation', 'value' => 75],
        ['id' => 5, 'status' => 1, 'rule_id' => 3, 'type' => 'ezlocation', 'value' => 155],
        ['id' => 6, 'status' => 1, 'rule_id' => 3, 'type' => 'ezlocation', 'value' => 156],
        ['id' => 7, 'status' => 1, 'rule_id' => 4, 'type' => 'ezcontent', 'value' => 70],
        ['id' => 8, 'status' => 1, 'rule_id' => 4, 'type' => 'ezcontent', 'value' => 71],
        ['id' => 9, 'status' => 1, 'rule_id' => 5, 'type' => 'ezcontent', 'value' => 72],
        ['id' => 10, 'status' => 1, 'rule_id' => 5, 'type' => 'ezcontent', 'value' => 73],
        ['id' => 11, 'status' => 1, 'rule_id' => 7, 'type' => 'ezchildren', 'value' => 72],
        ['id' => 12, 'status' => 1, 'rule_id' => 7, 'type' => 'ezchildren', 'value' => 73],
        ['id' => 13, 'status' => 1, 'rule_id' => 8, 'type' => 'ezsubtree', 'value' => 2],
        ['id' => 14, 'status' => 1, 'rule_id' => 8, 'type' => 'ezsubtree', 'value' => 43],
        ['id' => 15, 'status' => 1, 'rule_id' => 9, 'type' => 'ezsubtree', 'value' => 5],
        ['id' => 16, 'status' => 1, 'rule_id' => 9, 'type' => 'ezsubtree', 'value' => 13],
        ['id' => 17, 'status' => 1, 'rule_id' => 10, 'type' => 'ez_semantic_path_info', 'value' => '/the/answer'],
        ['id' => 18, 'status' => 1, 'rule_id' => 10, 'type' => 'ez_semantic_path_info', 'value' => '/the/other/answer'],
        ['id' => 19, 'status' => 1, 'rule_id' => 11, 'type' => 'ez_semantic_path_info_prefix', 'value' => '/the/'],
        ['id' => 20, 'status' => 1, 'rule_id' => 11, 'type' => 'ez_semantic_path_info_prefix', 'value' => '/a/'],
    ],
];
